name = "phoneedge"
main = "worker.js"   # 👈 This is your custom worker that handles fallback routing
compatibility_date = "2024-04-10"

[site]
bucket = "./dist"    # 👈 This is the folder where Vue builds your app
