name = "phoneedge"
type = "javascript"

[site]
bucket = "./dist"
entry-point = "."

[build]
upload.format = "modules"
upload.main = "worker.js"

[env.production]
route = "phoneedge.lymakara07012004.workers.dev/*"
