const products = [
  {
    id: 1,
    name: "Slim Fit Phone Case",
    category: "Phone Cases",
    price: 12.99,
    image: "products/slim-fit-case.jpg",
    description: "A sleek and protective case for your phone.",
    stock: 50,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Fast Charging Cable",
    category: "Chargers",
    price: 8.99,
    image: "products/fast-charging-cable.jpg",
    description: "Durable cable for fast and reliable charging.",
    stock: 100,
    rating: 4.7,
  },
  {
    id: 3,
    name: "Tempered Glass Screen Protector",
    category: "Screen Protectors",
    price: 6.99,
    image: "products/screen-protector.jpg",
    description: "High-quality tempered glass for ultimate protection.",
    stock: 200,
    rating: 4.8,
  },
  {
    id: 4,
    name: "Wireless Earbuds",
    category: "Headphones & Earbuds",
    price: 39.99,
    image: "products/wireless-earbuds.jpg",
    description: "Experience premium sound with our wireless earbuds.",
    stock: 30,
    rating: 4.6,
  },
  {
    id: 5,
    name: "10,000mAh Power Bank",
    category: "Power Banks",
    price: 24.99,
    image: "products/power-bank.jpg",
    description: "Compact and powerful power bank for long-lasting use.",
    stock: 75,
    rating: 4.7,
  },
];
