name: Notify Telegram on Push

on:
  push:
    branches:
      - main # You can change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d "text=🚀 *Push to GitHub:*%0A*Repository:* ${{ github.repository }}%0A*Branch:* ${{ github.ref_name }}%0A*Commit:* ${{ github.event.head_commit.message }}%0A*Author:* ${{ github.actor }}" \
          -d "parse_mode=Markdown" || echo "Failed to send Telegram notification"
