name: Notify Telegram on Push

on:
  push:
    branches:
      - main # You can change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d "text=🚀 *New push to the repository:*%0A  *Repository:* ${{ github.repository }}%0A  *Author:* ${{ github.actor }}%0A  *Commit message:* ${{ github.event.head_commit.message }}" \
          -d "parse_mode=Markdown" || echo "Failed to send Telegram notification"
